name       : xtrans
version    : 1.5.2
release    : 12
source     :
    - https://www.x.org/releases/individual/lib/xtrans-1.5.2.tar.gz : 23031301f10fef5eaa55b438610fbd29294a70d2fa189355343bf0186bff8374
license    :
    - MIT
homepage   : https://www.x.org/
summary    : X Network Transport Base Code
component  : xorg.library
patterns   : /
description: |
    xtrans is a library of code that is shared among various X packages to handle network protocol transport in a modular fashion, allowing a single place to add new transport types.  It is used by the X server, libX11, libICE, the X font server, and related components.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
