name       : hexchat
version    : 2.16.2
release    : 47
homepage   : https://hexchat.github.io/
source     :
    - https://github.com/hexchat/hexchat/releases/download/v2.16.2/hexchat-2.16.2.tar.xz : 2e88340a8da274b87373ec0740746da78120cc6fbfdd201a4dd6999cac790e4a
license    : GPL-2.0-or-later
component  :
    - network.irc
    - theme-manager : network.irc
summary    :
    - GTK+ IRC client
    - theme-manager : A theme manager for the hexchat IRC client
description:
    - HexChat is an IRC client based on XChat, but unlike XChat it’s completely free for both Windows and Unix-like systems.
    - theme-manager : A theme manager for the hexchat IRC client
patterns   :
    - theme-manager :
        - /usr/bin/thememan*
        - /usr/share/applications/io.github.Hexchat.ThemeManager.desktop
        - /usr/share/mime/packages/io.github.Hexchat.ThemeManager.xml
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(iso-codes)
    - pkgconfig(libcanberra)
    - pkgconfig(libpci)
    - pkgconfig(luajit)
    - pkgconfig(python3-embed)
    - mono-msbuild
    - python-cffi
rundeps    :
    - enchant
    - gtk2-engine-murrine
    - python-cffi
    - theme-manager :
        - hexchat
        - mono
setup      : |
    %patch -p1 -i $pkgfiles/0001-common-cfgfiles-Apply-Solus-defaults.patch
    %meson_configure -Dtheme-manager=true
build      : |
    %ninja_build
install    : |
    %ninja_install
