name       : xorg-driver-video-fbdev
version    : 0.5.1
release    : 32
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-fbdev-0.5.1.tar.gz : 5e73c01f6ede09ddbc1f553fecdf35dd8efe76b44c7ed263de786a5968c5116f
license    : MIT
component  : xorg.driver
homepage   : https://www.x.org/
summary    : Framebuffer Video Driver
description: |
    The Xorg Fbdev Driver package contains the X.Org Video Driver for framebuffer devices. This driver is often used as fallback driver if the hardware specific and VESA drivers fail to load or are not present.
optimize   :
    - no-bind-now
    - no-symbolic
builddeps  :
    - pkgconfig(pciaccess)
    - pkgconfig(xorg-server)
    - pkgconfig(xproto)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
