name       : gnome-mahjongg
version    : 47.0
release    : 12
source     :
    - https://download.gnome.org/sources/gnome-mahjongg/3.40/gnome-mahjongg-3.40.1.tar.xz : 8ed54eecade36b08336906fd8e6c902a0d6f7bbbbb67653c23956a6b631223f6
license    : GPL-2.0-or-later
homepage   : https://gitlab.gnome.org/GNOME/gnome-mahjongg
component  : games.card
summary    : Mahjongg is a solitaire (one player) version of the classic Eastern tile game, Mahjongg.
description: |
    Mahjongg is a solitaire (one player) version of the classic Eastern tile game, Mahjongg.
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(librsvg-2.0)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
